### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by koob** [CaTzil/service.subtitles.napisy24pl#12]
Po ostatnich zmianach (chyba już noworocznych) przestało działać wyszukiwanie napisów przez wtyczkę. Wygląda na to, że działa teraz tylko metoda POST w wyszukiwaniu. Zmieniłem sobie to w źródłach, błędów nie wyrzuca ale zwrócony content nie ma napisów. Może prościej byłoby skorzystać z ich API http://napisy24.pl/libs/webapi.php?title=Homeland%203x3 i parsować XMLa ? Nie wiem tylko na ile te API jest oficjalne, info znalezione na forum http://forum.napisy24.pl/viewtopic.php?f=26&t=226

**Comment by koob** [comment]
W zasadzie to poprawiłem, jutro postaram się dodać pullrequesta.

**Comment by CaTzil** [comment]
Pls,  next time write  in English

**Comment by CaTzil** [comment]
The XML is not valid, it should have one root node
