### ISSUE TITLE
API instead of parsing the site...

### ISSUE THREAD

**Issue by sake12** [CaTzil/service.subtitles.napisy24pl#19]
Maybe you can use their API instead of parsing HTML?

Link is:
http://napisy24.pl/libs/webapi.php?imdb=tt0068646
http://napisy24.pl/libs/webapi.php?title=Homeland%203x3

In return you get nice XML file...

**Comment by CaTzil** [comment]
There is a documentation of the API?

**Comment by sake12** [comment]
OK, so you have official API that uses hash to find subs, documentation is here:
http://forum.napisy24.pl/viewtopic.php?f=9&t=142

and "unofficial" that searches through names.
http://forum.napisy24.pl/viewtopic.php?f=26&t=226

You can see implementation of both here:
http://areq.eu.org/dmnapi/

**Comment by CaTzil** [comment]
I don't want to restrict to md5 hash, cause it not always right, (especially if you stream your content...)
The webapi.php?imdb=tt0068646 is irrelevant, Kodi doesn't give and IMDB Id.
http://napisy24.pl/libs/webapi.php?title=Homeland%203x3
This is kinda good, but it return none standard API, so all the XML parsers will break on it.

**Comment by d4m** [comment]
Some time ago I wrote an addon using the official API, but never published it.
https://github.com/d4m/service.subtitles.napisy24
