### ISSUE TITLE
The add-on is not downloading anything anymore

### ISSUE THREAD

**Issue by kokosowy** [CaTzil/service.subtitles.napisy24pl#21]
Hi CaTz, 

For your information, 1.0.11 version with most recent Kodi 17.0 is not downloading any subtitles anymore. Probably you would like to take a look. 

Thank you in advance for resolving this! 

Kind regards, 
Kokos

**Comment by kokosowy** [comment]
I mean it doesn't find any subtitle to download, sorry for inaccurate information. No error bubble visible on screen.

**Comment by CaTzil** [comment]
Thanx for the report, i will look into it.

**Comment by kokosowy** [comment]
Thank you!

**Comment by CaTzil** [comment]
Started to rewrite the add-on to fit to the new site.
almost finished TV-shows search

**Comment by kokosowy** [comment]
I'm so glad you reacted on this! Most of developers I met is not really eager to correct their plugins as their lose their interest in past projects.

**Comment by CaTzil** [comment]
@kokosowy Can you check if that version works for you?
There is an improvement when searching Tv-Show. :]

**Comment by kokosowy** [comment]
Hi,

Sorry, I had no time to test it earlier. There is no new version on Kodi repos so I downloaded 2.2.0 release from here.

It installed well, but unfortunately it still does not find any subtitles to download. [Here you can find kodi.log.](https://pastebin.com/iLZU6PCA)

Thank you and kind regards,
K

**Comment by CaTzil** [comment]
Hi, thanx for the report, now i see clearly what is the problem.

U are using some streaming service and it not parses the titles correctly, i can add a parsing mechanism, but i will near comp in 3 weeks only.

U can try to open an issue on the service repo, it is a bug there.

**Comment by kokosowy** [comment]
Hi again CaTzil,

Actually it's not a streaming service. This is just NFS server in my LAN. However I get your point. These video items are not processed by Kodi in any way and not added to library, these are just files on file-system. This is way I prefer accessing files that were downloaded automatically.

Parsing mechanism would be wonderful if this is not a biggie for you. Thanks a lot!

Later on I will check whether n24 plugin can download subtitles for items in my Library, but for that I will need tu use my living-room Kodi and kids are occupying this a lot. :-)

Thanks again!
K

**Comment by CaTzil** [comment]
So this is the problem... :)
I've already implemented the parser on other subs service, so it would be easy to reimplement it at 24pl service

**Comment by kokosowy** [comment]
That's fantastic! Thank you for that! Once tested remember to push it to Kodi repo. :-)

**Comment by kokosowy** [comment]
I've just checked.. For items in library downloading of subtitles works just fine with version.. v1.0.11.

So I'm terribly sorry I reported this as bug.. I don't know why, but I thought downloading subtitles was working with items outside the library...

I hope it was not a big deal for you as I know you produced new version.. Anyways, I will be very happy to see new version with parser someday.

Cheers,
K

**Comment by CaTzil** [comment]
The new version contains optimization for TV show search, it much accurate and faster.
Try it on in library items, and tell me if there is any issue with the new implementation.

**Comment by kokosowy** [comment]
I've just checked briefly for now. It works very nice and quickly. One thing I'd change is to not release a notification with information that logon to the website was successful, as it appears every time we download the subs. I don't think it's necessary. It can be helpful just for troubleshooting purposes.

**Comment by CaTzil** [comment]
You are right, good catch.
Will fix it when ever add the parsing stuff.
Can u review the polish translation file, if it Ok?

**Comment by kokosowy** [comment]
Just reviewed it, seems good to me.

**Comment by CaTzil** [comment]
@kokosowy try the latest release, it contains title parsing.
It should work also for TV-shows.

**Comment by kokosowy** [comment]
Parser works great! However, I still receive logon notification each time I download the subtitle.

Thanks!

**Comment by CaTzil** [comment]
Regarding the login notification, can u empty the addon`s data folder, this will remove the cookies.
And then try to login trough the settings.

I`m not getting that notification cause i`m already logged in

**Comment by CaTzil** [comment]
Can i publish the latest version?

**Comment by kokosowy** [comment]
Sorry, please give me one more day. I will check once possible. Thanks.

**Comment by kokosowy** [comment]
Sorry for late response, CaTzil.. No good news, I've removed plugin dir from userdata folder, input credentials again and I still get the notification about the logon every time I download the subs. I also removed the plugin completely and installed it again. Same thing. :( I will try to check it on other computer tomorrow.

**Comment by kokosowy** [comment]
Weird.. Same on my other Linux machine worked. I've removed addon completely, closed Kodi, removed plugin folder from userdata installed latest release, configured it and it works. Got only one notification...

I will try again with my Android box soon.

**Comment by kokosowy** [comment]
Ha! Now works as supposed on both systems. The only difference in my procedure is that I needed to remove/reinstall addon, not just recreate plugin folder in userdata.

Maybe before releasing unsure there is no issue with upgrade from 1.x to 2.x version.

**Comment by CaTzil** [comment]
Cool, from the code it not suppose to notify each time :].
Thank you.
I will publish that.
