### ISSUE TITLE
Wtyczka przestała działać w Kodi 19

### ISSUE THREAD

**Issue by yabba235** [CaTzil/service.subtitles.napisy24pl#23]
wtyczka nie działa w wersji kodi 19   -  nie jest kompatibilna  z python3

**Comment by CaTzil** [comment]
Hi, english pls :]

I didn't tested it yet.

**Comment by yabba235** [comment]
This addon not work under kodi 19 - mayby is incompatibile with python3.

**Comment by CaTzil** [comment]
Correct this addon not supports python 3...
I'm looking into guides of how to migrate.

**Comment by CaTzil** [comment]
I don't see any subtitle addon that supports python 3 yet...

**Comment by yabba235** [comment]
Ah, this is serious problem - Kodi 19 is ONLY python3 compatibile.
I have another subtitles addon; opensubtitles.org  and napiprojekt.pl - both working fine in kodi 19.

**Comment by felixmosh** [comment]
this one?
https://github.com/CaTzil/service.subtitles.napiprojekt
:]

**Comment by yabba235** [comment]
yes, CaTz 1.1.3

sob., 9 lis 2019 o 17:34 Felix Mosheev <notifications@github.com>
napisał(a):

**Comment by yabba235** [comment]
Any news about working version addon under kodi 19 ?

**Comment by CaTzil** [comment]
Sorry, I didn't had time to look into it...

**Comment by yabba235** [comment]
In Kodi 18.5 not work too.
Very sad for no time to develop this addon.
Generaly your addon not work under python3 ( napisproject too not work ) :(

**Comment by CaTzil** [comment]
Looks like the website is not allowing to download any subs from the web interface any more.
![image](https://user-images.githubusercontent.com/3762838/70800738-aa335b80-1db5-11ea-97b5-686fc7581fc0.png)

**Comment by yabba235** [comment]
OK, but native app is scrap, I don't use it no more ( and is only for
windows, no linux version, so is useless ).

pt., 13 gru 2019 o 13:35 CaTz <notifications@github.com> napisał(a):

**Comment by yabba235** [comment]
from kodi 19 alpha1 log addon error:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: 'str' object has no attribute 'decode'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.napiprojekt/service.py", line 27, in <module>
                                                __cwd__ = xbmc.translatePath(__addon__.getAddonInfo('path')).decode("utf-8")
                                            AttributeError: 'str' object has no attribute 'decode'
                                            -->End of Python script error report<--
2020-01-03 17:59:15.425 T:1156 WARNING: CPythonInvoker(5, /storage/.kodi/addons/service.subtitles.napiprojekt/service.py): the python script "/storage/.kodi/addons/service.subtit$
2020-01-03 17:59:15.434 T:1074   ERROR: GetDirectory - Error getting plugin://service.subtitles.napiprojekt/?action=search&languages=Polish&preferredlanguage=Polish
2020-01-03 17:59:17.453 T:1157   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: 'str' object has no attribute 'decode'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.napisy24pl/service.py", line 21, in <module>
                                                __cwd__ = xbmc.translatePath(__addon__.getAddonInfo('path')).decode("utf-8")
                                            AttributeError: 'str' object has no attribute 'decode'
                                            -->End of Python script error report<--
2020-01-03 17:59:17.554 T:1113   ERROR: GetDirectory - Error getting plugin://service.subtitles.napisy24pl/?action=search&languages=Polish&preferredlanguage=Polish

Error from both addons napiproject and napisy24.

**Comment by CaTzil** [comment]
If there is no ability to download subs from the site it-self I can't help here.

**Comment by yabba235** [comment]
I can download the subtitles from the site, but this is the plugin to do it
from Kodi, so you need to improve the plugin to finally work, because it
doesn't work.

If you can't fix your own plugin, just write explicitly that it stops
working in future Kodi versions.

śr., 8 sty 2020 o 10:06 CaTz <notifications@github.com> napisał(a):

**Comment by yabba235** [comment]
I already know what the mistake is - you suggested the subtitles, which are
only available from the program level, and that's wrong, because on this
page there are also subtitles normally available for download - it's only a
matter of time - subtitles are always available first to download the
program, only later you can download it yourself.

śr., 8 sty 2020 o 10:06 CaTz <notifications@github.com> napisał(a):

**Comment by CaTzil** [comment]
Can you share a subtitle page that allows me to download **from the site**?

**Comment by CaTzil** [comment]
@yabba235 can you test [v3.0.0](https://github.com/CaTzil/service.subtitles.napisy24pl/releases) ?

**Comment by yabba235** [comment]
> @yabba235 can you test [v3.0.0](https://github.com/CaTzil/service.subtitles.napisy24pl/releases) ?

Not yet, now I'm in my work so testing tonight.

**Comment by yabba235** [comment]
Yes I'm testing now and.. is working !
But no find any subs, even existing.
Most important that addon working without errors.


pt., 10 sty 2020 o 13:06 CaTz <notifications@github.com> napisał(a):

**Comment by CaTzil** [comment]
Glad to hear!
Thank you for testing it :]

**Comment by CaTzil** [comment]
Published on official repo https://github.com/xbmc/repo-scripts/pull/1267
