### ISSUE TITLE
Addon doesnt work (?) since Kodi 19

### ISSUE THREAD

**Issue by Dinth** [CaTzil/service.subtitles.napisy24pl#27]
Hi. I was happy to see this addon be one of the first subtitle addon upgraded to Kodi 19/Python 3 a while ago. Unfortunately, i have never managed to get Python3 version to work since then.
Logging in works fine, same with search, but when i try to download any subtitle im getting an error.
Looking at kodi.log:
`CUtil::SplitParams("C:\XXX\Kodi\iserdata\addon_data\service.subtitles.napisy24pl\temp\subs.zip", C:\XXX\Kodi\userdata\addon_data\service.subtitles.napisy24pl\temp") - end of string while searching for ) or "
`

**Comment by CaTzil** [comment]
Hi @Dinth 
Thank you for reporting an issue, 🙏🏼
Yesterday, I've tried to fix it, seems that it related to unzipping the archive.
I didn't able to find a working method to extract the subs from zip files

**Comment by pogo1975** [comment]
hi @CaTzil i worked around this problem
find the attached changed files, i think it is required to include urllib i addon.xml but i do not know this for certain,

Think that required changes are only in NapisyUtils.py but this is my firs ever "hack" of python script, so it needs checking, code is borrowed from another plugin "subscene"

Regards 
Jarek
[changes.zip](https://github.com/CaTzil/service.subtitles.napisy24pl/files/6056935/changes.zip)

**Comment by CaTzil** [comment]
Does it work for you?

Can you check if downloading subs of 2 separate video files? I've used
something similar and it works only for the first time, downloading subs to
a second file throws an error

**Comment by pogo1975** [comment]
as much as i can check it is working, downloaded couple of subtitles for diffrent tv shows without error

**Comment by CaTzil** [comment]
Thanks, I'll check it out asap

**Comment by CaTzil** [comment]
I've tested your code, it throws 
```
Create - unsupported protocol(archive) in archive://
```
![image](https://user-images.githubusercontent.com/3762838/109533786-459c1380-7ac3-11eb-8b20-f003a114f1e1.png)

I've tried similar solution (which i've copied from one of the addons) with zip protocol, and it works, but only once.

Maybe, there is some issue with my setup, I will try to setup a regular dev env, if it solves the basic usage I will upload a fix.

**Comment by CaTzil** [comment]
Fixed in v3.0.2
