### ISSUE TITLE
zip extraction on windows fails, wrong slash

### ISSUE THREAD

**Issue by ciukacz** [CaTzil/service.subtitles.napisy24pl#28]
NapisyUtils.py, line 148:
```python
flag = xbmcvfs.copy(os.path.join(zip_filepath, file), filename_dest)
```
here os.path.join() adds backslash instead of a forward slash and extraction fails.
```python
filename_src = zip_filepath + '/' + file
flag = xbmcvfs.copy(filename_src, filename_dest)
```
works and is still platform independent

**Comment by CaTzil** [comment]
Thanx for reporting this, I don't have a PC :}

I will push this fix asap

**Comment by CaTzil** [comment]
@ciukacz 
can you check if the delete temp files is workings as it is?
```python
        if xbmcvfs.exists(__temp__):
            (dirs, files) = xbmcvfs.listdir(__temp__)
            for file in files:
                xbmcvfs.delete(os.path.join(__temp__, file))
        else:
            xbmcvfs.mkdirs(__temp__)
```

**Comment by ciukacz** [comment]
yes it works here because it is a regular path, the issue with zip:// is that it requires forward slash after the archive name

**Comment by CaTzil** [comment]
Cool, thank you

**Comment by CaTzil** [comment]
https://github.com/xbmc/repo-scripts/pull/1900

**Comment by CaTzil** [comment]
@ciukacz , can you change the line to 
```python
flag = xbmcvfs.copy(xbmcvfs.validatePath(os.path.join(zip_filepath, file)), filename_dest)
```

And test the plugin 🙏🏼

**Comment by ciukacz** [comment]
@CaTzil it fails under windows
