### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by newkind** [CaTzil/service.subtitles.napisy24pl#33]
I just tried to setup the addon on my two devices - CoreElec and MacOS and I cannot login. I always end up with "Invalid credentials" error. Looks like the addon might need an update.

Thanks!

**Comment by newkind** [comment]
@CaTzil fix confirmed. Thank you very much! :)

**Comment by CaTzil** [comment]
Thank you for testing this. I'll publish a version.
